name: Sonar Analysis via Gradlew
on:
  workflow_call:
    inputs:
      SERVICE_LOCATION:
        description: 'SERVICE LOCATION'
        required: true
        type: string
      ANDROID_LOCATION:
        description: 'ANDROID LOCATION'
        required: true
        type: string
      SONAR_URL:
        required: false
        type: string
        default: 'https://sonarcloud.io'
      PROJECT_KEY:
        required: false
        type: string
        default: "mosip_${{ github.event.repository.name }}"
      PROJECT_NAME:
        required: false
        type: string
        default: "${{ github.event.repository.name }}"
      SONAR_ARGS:
        required: false
        type: string
        default: ""
      RELEASE_KEYSTORE_ALIAS:
        default: androidreleasekey
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_ORGANIZATION:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      ANDROID_KEYSTORE_FILE:
        required: true
      RELEASE_KEYSTORE_PASSWORD:
        required: true

env:
  ANDROID_HOME: '/opt/android-sdk/'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
  SONAR_URL: ${{ inputs.SONAR_URL }}

jobs:
  gradlew-sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - uses: actions/setup-node@v3.7.0
        with:
          node-version: '16'

      - name: NPM Install Dependencies
        run: cd ${{ inputs.SERVICE_LOCATION }} && npm install

      - name: Check if Environmental variables set for sonar
        run: | 
          if [[ -z $SONAR_TOKEN ]]; then
            echo "\$SONAR_TOKEN environmental variable not set; EXITING;";
            exit 1;
          fi
          if [[ -z $SONAR_ORGANIZATION ]]; then
            echo "\$SONAR_ORGANIZATION environmental variable not set; EXITING;";
            exit 1;
          fi
          if [[ -z $SONAR_URL ]]; then
            echo "\$SONAR_URL environmental variable not set; EXITING;";
            exit 1;
          fi
          echo "After installing dependencies" && df -h

      - name: Generate keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > release.keystore.b64
          base64 -d -i release.keystore.b64 > android/app/release.keystore
          echo "After Generate keystore" && df -h 
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}

      - name: Analysis with Sonarcloud
        run: |
          echo "Starting Analysis with Sonarcloud" && df -h
          cd ${{ inputs.SERVICE_LOCATION }}/${{ inputs.ANDROID_LOCATION }}
          sed -i -e 's/\r$//' ./gradlew
          chmod +x ./gradlew
          ./gradlew build sonarqube -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} -Dsonar.projectKey=${{ inputs.PROJECT_KEY }} -Dsonar.projectName=${{ inputs.PROJECT_NAME }} -Dsonar.host.url=${{ inputs.SONAR_URL }} --info --warning-mode all ${{ inputs.SONAR_ARGS }}
          echo "Starting Analysis with Sonarcloud" && df -h
        env:
          RELEASE_KEYSTORE_ALIAS: ${{ inputs.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEYSTORE_PASSWORD: "${{secrets.RELEASE_KEYSTORE_PASSWORD}}"

      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      #   if: failure() # Pick up events even if the job fails or is canceled.